# Generated by Django 5.1.3 on 2024-11-13 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('province', models.CharField(choices=[('province 1', 'Province 1'), ('province 2', 'Province 2'), ('province 3', 'Province 3'), ('province 4', 'Province 4'), ('province 5', 'Province 5'), ('province 6', 'Province 6'), ('province 7', 'Province 7')], max_length=20)),
                ('country', models.CharField(default='Nepal', max_length=20)),
                ('primary_industry', models.CharField(choices=[('Software', 'Software'), ('Finance', 'Finance'), ('Education', 'Education'), ('Customer Service', 'Customer Service')], max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=20)),
                ('company_size', models.CharField(max_length=20)),
                ('founded_in', models.PositiveIntegerField()),
                ('linkedin', models.URLField()),
                ('website', models.URLField()),
                ('instagram', models.URLField()),
                ('facebook', models.URLField()),
                ('about_company', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
