# Generated by Django 5.1.3 on 2024-11-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
