# Generated by Django 5.1.3 on 2024-11-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='school_name',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('None', 'None'), ('SEE', 'SEE'), ('SLC', 'SLC'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Diploma', 'Diploma'), ('PHD', 'PHD')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.CharField(choices=[('None', 'None'), ('SEE', 'SEE'), ('SLC', 'SLC'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Diploma', 'Diploma'), ('PHD', 'PHD')], max_length=200),
        ),
    ]
