# Generated by Django 5.1.3 on 2024-11-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_education_course_alter_education_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='address',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='course',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
