# Generated by Django 5.1.3 on 2024-11-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_education_address_alter_education_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='address',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='course',
            field=models.CharField(max_length=50),
        ),
    ]
