# Generated by Django 5.1.3 on 2024-11-22 02:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_work_address_alter_education_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='work',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('proficiency_level', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume.resume')),
            ],
        ),
    ]
