# Generated by Django 5.1.3 on 2024-11-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobExperiecnce',
            new_name='JobExperience',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='user',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='job',
            name='date_posted',
        ),
        migrations.AlterField(
            model_name='job',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
